#!/bin/bash

echo -n "Loading $PWD/common.sh... "
source "$PWD/common.sh"

install "Updating apt sources" apt-get update

if ! which git >/dev/null; then
    install "Installing git" apt-get install -y git
fi

if ! which bundler >/dev/null; then
    install "Installing bundler" apt-get install -y ruby-bundler
fi

if apt-cache policy ruby-dev | grep '(none)' >/dev/null; then
    install "Installing ruby-dev" apt-get install -y ruby-dev
fi

mkdir -p "$INSTALL_PATH"
install "Switch to $INSTALL_PATH" cd "$INSTALL_PATH"

if test ! -d puppet-ws; then
    install "Clonning puppet-ws" git clone https://github.com/fuco1/puppet-ws.git
fi

install "Switch to $INSTALL_PATH/puppet-ws" cd puppet-ws

if [ -z "$NO_RUN" ]; then
    ./run
fi
