#!/bin/bash

echo "Loading $PWD/common.sh"
source "$PWD/common.sh"

[ -z "$SKIP_BUNDLER" ] && install "Install ruby bundle" bundle install --path vendor/bundle --binstubs
[ -z "$SKIP_LIBRARIAN" ] && install "Install puppet bundle" ./bin/librarian-puppet install
install "Run puppet" ${SUDO} \
        FACTERLIB="$PWD/facts" \
        ./bin/puppet apply \
        --confdir="$PWD" \
        --modulepath="$PWD/local-modules:$PWD/modules:/usr/share/puppet/modules" \
        "$NOOP" \
        "$MANIFEST"
